### ISSUE TITLE
请问下mupdf版本

### ISSUE THREAD

**Issue by AndyGu** [xiaolongonly/MuPdfForAndroid#1]
mupdf的library是您自己编译的么，请问下是哪个mupdf的版本呢，另外可不可以在博客中写一下如何build一个library？感谢

**Comment by guoxiaolongonly** [comment]
@AndyGu 不是我编译的，对NDK编译没什么研究，还在学习中。希望与大家互相学习，共同进步~ 嘻嘻~

**Comment by liupeng826** [comment]
muPdf是不能用于商业用途的吧？
